version: "3.3"

services:
  nginx:
    build: .
    container_name: nginx
    healthcheck:
      test: curl http://localhost:80
      interval: 1s
    restart: unless-stopped
    networks:
      - ocelot-net

networks:
  ocelot-net:
    external: true