services:
  store:
    image: ocelotcloud/store:local
    container_name: ocelotcloud_store_store
    environment:
      - PROFILE=${PROFILE}
    # TODO !! port should actually be hidden by traefik in production, so I need two configs
    ports:
      - 80:8080

  postgres:
    image: postgres:17.2
    container_name: ocelotcloud_store_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
    ports:
      - 127.0.0.1:5432:5432
    tmpfs:
      - /var/lib/postgresql/data

networks:
  ocelotcloud_store:
    name: ocelotcloud_store
# TODO !! should be an external network for app integration?