services:
  postgres:
    image: postgres:17.2
    container_name: ocelotcloud_appstore_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
    ports:
      - "127.0.0.1:5433:5432"
    restart: unless-stopped
    tmpfs:
      - /var/lib/postgresql/data