services:
  maliciousapp:
    image: nginx/nginx:1.20.2
    container_name: maliciousmaintainer_maliciousapp_maliciousapp
    # malicious attempt to get root access via docker socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
