services:
  nginx:
    image: nginx/nginx:1.20.2
    container_name: sampleuser_nginx_nginx
    # malicious attempt to get root access via docker socket
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
