networks:
    samplemaintainer_gitea:
        external: true
services:
    gitea:
        cap_add:
            - CAP_NET_BIND_SERVICE
            - CAP_CHOWN
            - CAP_FOWNER
            - CAP_SETGID
            - CAP_SETUID
            - CAP_DAC_OVERRIDE
        cap_drop:
            - ALL
        container_name: samplemaintainer_gitea_gitea
        image: gitea/gitea:1.20.2
        networks:
            - samplemaintainer_gitea
        restart: unless-stopped
