name: CI

on:
  push:
    branches:
      - '**'

permissions:
  contents: read

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup

      - name: Run CI Tests
        run: |
          cd src/ci-runner
          go build
          ./ci-runner download
          ./ci-runner test all
